AWSTemplateFormatVersion: '2010-09-09'
Description: AWS-Sensei Pipeline (Source → InfraDeploy → BuildDeployHugo)

Parameters:
  ArtifactBucketName:
    Type: String
    Description: S3 bucket used for CodePipeline artifacts

  CodePipelineRoleArn:
    Type: String
    Description: IAM role ARN for CodePipeline

  CloudFormationExecutionRoleArn:
    Type: String
    Description: IAM role ARN used by CloudFormation during SAM deploy

  HugoBuildProjectName:
    Type: String
    Description: CodeBuild project name for Hugo build

  GitHubOwner:
    Type: String
    Default: AWS-Sensei

  GitHubRepo:
    Type: String
    Default: Blog

  GitHubBranch:
    Type: String
    Default: main


Resources:
    
  AWSSenseiBlogPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !Ref CodePipelineRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucketName
        EncryptionKey:
          Type: KMS
          Id: alias/aws/s3
      Stages:
        # ----------------------------------------------------------
        # SOURCE STAGE
        # ----------------------------------------------------------
        - Name: Source
          Actions:
            - Name: GitHub_Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                ConnectionArn: "arn:aws:codeconnections:eu-central-1:804711834430:connection/fb8bbf59-fe32-4dd1-8a5b-a1d2642a5fb9"
                FullRepositoryId: !Sub "${GitHubOwner}/${GitHubRepo}"
                BranchName: !Ref GitHubBranch
                DetectChanges: true
        # ----------------------------------------------------------
        # INFRASTRUCTURE DEPLOY (SAM)
        # ----------------------------------------------------------
        - Name: InfraDeploy
          Actions:
            - Name: SAM_Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: AWS-Sensei-Blog
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                TemplatePath: SourceOutput::infrastructure.yaml
                RoleArn: !Ref CloudFormationExecutionRoleArn
              Namespace: AWSSenseiBlogVariables
        # ----------------------------------------------------------
        # HUGO BUILD & DEPLOY
        # ----------------------------------------------------------
        - Name: BuildDeployHugo
          Actions:
            - Name: Hugo_Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref HugoBuildProjectName
                EnvironmentVariables: |
                  [
                    {
                      "name": "WEBSITE_BUCKET",
                      "value": "#{AWSSenseiBlogVariables.WebsiteBucketName}",
                      "type": "PLAINTEXT"
                    },
                    {
                      "name": "CLOUDFRONT_DISTRIBUTION_ID",
                      "value": "#{AWSSenseiBlogVariables.CloudFrontDistribution}",
                      "type": "PLAINTEXT"
                    }
                  ]
