AWSTemplateFormatVersion: '2010-09-09'
Description: Master stack that orchestrates all nested stacks for AWS Sensei Blog CI/CD

Resources:

  # --------------------------
  # Foundation Layer
  # --------------------------
  FoundationRoles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: foundation/roles.yaml

  FoundationArtifacts:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: foundation/artifacts.yaml
      
  # --------------------------
  # Pipeline Layer
  # --------------------------
  CICDPipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: pipeline/pipeline.yaml
      Parameters:
        CodePipelineRoleArn: !GetAtt FoundationRoles.Outputs.CodePipelineRoleArn
        CloudFormationExecutionRoleArn: !GetAtt FoundationRoles.Outputs.CloudFormationExecutionRoleArn
        ArtifactBucketName: !GetAtt FoundationArtifacts.Outputs.ArtifactBucketName