AWSTemplateFormatVersion: '2010-09-09'
Description: AWS-Sensei Pipeline (Source → InfraDeploy → BuildDeployHugo)

Parameters:
  ArtifactBucketName:
    Type: String
    Description: S3 bucket used for CodePipeline artifacts

  CodePipelineRoleArn:
    Type: String
    Description: IAM role ARN for CodePipeline

  CloudFormationExecutionRoleArn:
    Type: String
    Description: IAM role ARN used by CloudFormation during SAM deploy
    
  PackageBuildProjectName:
    Type: String
    Description: CodeBuild project name for Cloudformation Package build
    
  WebAppBuildProjectName:
    Type: String
    Description: CodeBuild project name for Web App build

  GitHubOwner:
    Type: String
    Default: AWS-Sensei

  GitHubRepo:
    Type: String
    Default: Flashcard-App

  GitHubBranch:
    Type: String
    Default: main


Resources:
    
  AWSSenseiFlashcardAppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !Ref CodePipelineRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucketName
        EncryptionKey:
          Type: KMS
          Id: alias/aws/s3
      Stages:
        # ----------------------------------------------------------
        # SOURCE STAGE
        # ----------------------------------------------------------
        - Name: Source
          Actions:
            - Name: GitHub_Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: "{{resolve:secretsmanager:GitHub-Connection:SecretString:token}}"
        # ----------------------------------------------------------
        # HUGO BUILD & DEPLOY
        # ----------------------------------------------------------
        - Name: Build
          Actions:
            - Name: PackageTemplate
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref PackageBuildProjectName
                EnvironmentVariables: !Sub |
                  [
                    {
                      "name": "ARTIFACT_BUCKET",
                      "value": "${ArtifactBucketName}",
                      "type": "PLAINTEXT"
                    }
                  ]
        # ----------------------------------------------------------
        # INFRASTRUCTURE DEPLOY (SAM)
        # ----------------------------------------------------------
        - Name: InfraDeploy
          Actions:
            - Name: SAM_Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              OutputArtifacts:
                - Name: InfraOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: AWS-Sensei-Flashcard-App
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                TemplatePath: BuildOutput::packaged.yaml
                RoleArn: !Ref CloudFormationExecutionRoleArn
              Namespace: AWSSenseiFlashcardAppVariables
        # ----------------------------------------------------------
        # HUGO BUILD & DEPLOY
        # ----------------------------------------------------------
        - Name: BuildDeployWebApp
          Actions:
            - Name: WebApp_Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref WebAppBuildProjectName
                EnvironmentVariables: |
                  [
                    {
                      "name": "WEBSITE_BUCKET",
                      "value": "#{AWSSenseiFlashcardAppVariables.FlashcardWebAppBucketName}",
                      "type": "PLAINTEXT"
                    },
                    {
                      "name": "CLOUDFRONT_DISTRIBUTION_ID",
                      "value": "#{AWSSenseiFlashcardAppVariables.FlashcardWebAppCloudFrontDistribution}",
                      "type": "PLAINTEXT"
                    }
                  ]
